[package]
name = "oxid8"
version = "0.1.0"
edition = "2024"
description = "CHIP-8 interpreter."
license = "MIT"

[dependencies]
oxid8-core = "0.1.0"
crossterm = "0.29.0"
indoc = "2.0.6"
ratatui = "0.29.0"
signal-hook = "0.3.17"
