[package]
name = "oxid8-wasm"
version = "0.1.0"
edition = "2024"
authors = ["Ethan Dibble <edibble@pdx.edu>"]
description = "WASM buttons for oxid8-wgpu."
repository = "https://github.com/edibblepdx/Oxid-8"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
oxid8-core = { path = "../oxid8-wgpu"}
wasm-bindgen = "0.2.100"

[workspace]
